apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Ef3K9VykYdfUgvDXkKCeLHXNQgMbLhQNNdcfjAuIOBv336SUchDLVg==,iv:K7SDz1ddU0pXPI83mIMNvdGKYO7WGOhymATcPxURLvE=,tag:ZQXxVfIT6qNzHl+tJHjCNw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEcEFlT1hhdm4yNDh0SDg5
            NCtzVWZEeTlaV0RoM2JtbllHbFBWUm9jeWpvCnQyUkVDYVhiMExaR3hpd0c5dkdP
            b3FGTHNHd0Y0QkFDWFhyU3RQYWk2Z00KLS0tIFYvV1puTjFVRzhCRGJ6Ump6OU9y
            c0Z6dS9PQVZDK2svbm10WVB3cnlmbFEKvoxQiYZMRs3h/JSKIS4VCtPqRMSuvjbj
            r+RhYl7GQ8ImyT+hqNGCMTnEGLEh9dsEtnEAuGrmEG1OYAAcI3SlPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T20:54:55Z"
    mac: ENC[AES256_GCM,data:fG/vaIHD84J3GRG0nBXJ7PFlOT0JN9YXgG+4hG7wrZleT3wlqvPqE3/9J1K9orC+Co0r3a8v76RSyIGwU77yt9bVP8RgKQhGvinrGzdpbYq+VF3IVugQzO71ZB/hJEJyhNjwY38qQNmHjveF6Ebydf0AtKpmM+lkUPDO5K+y0yU=,iv:z0DDug263FjZZeo/iq9o7mA+Zagmjm8wfOGee0a4uP8=,tag:YvhiNDPW3EYTrbkRL3eyfg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
