apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:MlbFsPe/R9atdrxqJwN4062UNucJ4UiwdaxK/uZtxzCEF2RSHPcl2A==,iv:XfMakoUPECXgr6NgjyXt0Mb1OmO+HpDdH7im8Lfb6aw=,tag:U5/QwQVoAkGQe+2KdRVwPQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdFNzQm5sMURWY3hoQ2s4
            dG8vZUxvaTdzU01YbGN0TEFvclFtSVo2Qmg4ClVtN3ZUWnJrd3RKTjJNbGtlVG03
            U0hNbCtZM2tSaHl1VGNvc1B3enNuc0kKLS0tIDZ2NVgwM0tueVZGU21ycEpEWXRJ
            YmZBekV5SWVFM2lMaElPaUh5STRFUm8KaMVmXpIPvecNMl0NuomSRh2G5vTE1mOD
            HKNlTDJwnESVr9WW5Kj8tBAFo4HDs7yyYTWoIJClYo+js9Ed/p5HRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T14:44:25Z"
    mac: ENC[AES256_GCM,data:ZDIe+gNj3N9jDsRojuLOoWUEdiUW8xrEGI913Vw9jdQ9lHuU7sUOvK3gihJog4g4o7NSmI4T2FwUJkxiU72NWNkDjDFGBd7BzNmayh6A5SLb0Jf1pTuTKZYC/kISDW4J7kMCQY41JndZO4Yp+nQWabTsref8FO9Wg9rmhyGtSq0=,iv:F/wfDV8VKUeAK2qyzHwBMzRoKyhQ3esjDsMRjkim/yk=,tag:YVG98IxMEo1iMLDwNKmbuQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
