apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:eQmFhMW3d3VoOPuhviqD9+OesetUK/CcD0yRClRUF3JoPD4Qx911Uw==,iv:ZPxJ5oouAsVvoc2OtQofDFnJSIXL/rpSdOYGV9Uc3Aw=,tag:sfq+P9e9K1gd7iY4aa9OgA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Y0JOeWs4QWlwTHI5R251
            UDRhRFNERERZR3lIMHNUcnU3LzFpai8zNWdZClBKTFMzWmxjQ3hFcXpua2VGUEJW
            K1JFOHc3Q1RHeFFNSnJwNkJkeTJNTWMKLS0tIG5zaTNkSWNpV0x2WEd6aURBeGdl
            blplR0d1UDhKYk43RW1DMjZycVZEMEUKRanroERwpuuiIbmAoFe8QcPmSFSZ07c2
            T/eUw25AkZW74uharu4aVr2hkGAlRk28hxB3gA/mJsbU94RWiJyO0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T20:49:51Z"
    mac: ENC[AES256_GCM,data:LbfmUsaG97fjeqDNCA3WFT2VXiOArd7JHdQDEE7PJnL4kPNVxfa4VSKRTsjFLNv33jlXRFT4+stEuNjyEvD0YKLH1WFcUJAQUBjD82Syv4BdxZejvtHgasG6orrftck41YJcThEzl39Gt/SipsMWmbe7/qe3hzltc3ijhmtBez0=,iv:2ZwYNJWGJn+xqZQCxTcEBrBlF4RyaVjaoOrDdLAlv20=,tag:f+JC4uf3puJXOGPAMaZ7RA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
