apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:mI03+8IAoUWUdFBz645lHqQRU5f+CFyRXJb/lUvnK5UNxLPFfAWuUg==,iv:u9MfTpuw0eXTk7x1ne0Yb0MeLcpBcp0n7bs2kg7TeIY=,tag:EhVor/68zdVxG0j/UJ8LQw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYmh0KytoOEFNWDlsWEhR
            SUtXS3VuVHUySDN5MnY0MlNINGlldW9uWnpJCml5cyt3RmpzR3NkTlBNZDJaT1J3
            Uml0MWwwWmlLVTk1VVVHN0FCczNJN28KLS0tIFNnNjFSU2w0dmJ3WVFTbGNxV2l2
            UnFDdlIrV0IwZWpXN0N4aDNnajVCeTgKHnFxsRwgxCFB36domkonFipUohFEQgM8
            Y1oBj7NUsPN8eM48uBAwea2zqooG8mSOLspi3VBVvBiK9dQYoz8riQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T21:19:33Z"
    mac: ENC[AES256_GCM,data:sQygjCl1BvfvYwUWjMkMPf2mqnxR7ktP4cXb3TrL5eoF9j7AohgC99+ule5esg9yRAL1HCYLYAJ7EaZpvpY+QeuZ9pxvjDSN3RRrvV+6C5+BkYcArrf+Uzvi5iqYz0VtJ02+VvSB0LNwQ6WR3uVI8x6jgZbXCG4d1xv8KROx708=,iv:jLYJdQukdGTC504jsiuriTudyPbyEA2DFB6K4sh67g4=,tag:CuUA0gg0Vv9qJj5FOXpmig==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
