apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:8bDUiF4SR7Bx1exypriEjjp6pgNHbRc2NRjuAW7rGkCtO2vA3L4/iyRBx5fwO6e5P7QwHKEykg28XIHd8JKXp8wWGInWK8L99u6bybTBDBeg4/yQVebfTy5fO6wsSEka7IypekTKXZ11yoaGafZr0Jr6LuyGcipUnPK/RhPXIIAvZJl4saSdpHy1mqeqaRmo9uPLdDT+mFykYgVsdhrynBpLz/vZIoJLNkAe9mLHzbo+WcIfi5F8OMD3kqTzU2OrmbPp5Qq57J63RKq33WcoSLPvIo0PuUIDqcESfftxmSMW5rUxmiHNwQpgrCKnNdl7cNQlDEEEFB+IhQ5m6eVLrtRdlHAJ57cyzEaFLFSRNu72tTo44NMAh7k7kV8ChoDQ,iv:PrydztbNjTxvyvldgOS4L+UPT3xcWxEH5D0IUEdqlnk=,tag:JxbiZPjzS/aclxmNklgteg==,type:str]
    identity.pub: ENC[AES256_GCM,data:eAn7SNMRsXpzXq7Y4cgQwUDBIpAihK8UjjQZ9/C31GSiv9K6CJUJnUSGUG9vUn41t54qlDQADft87Y8TA3ZtiRYMY8s88Je8Wtfb9Eil8Y6AfKKi8Ej6Mmm8zm7dr3r2xkQXR8NKy7l/Fmm25Jg8Px9zaqHNWCQJsY1Rp0dYGKxVTViv6/Cm8GAZf1dG6YmgcO72AC7n3zmsj+aLhEMgIYkup0p6AefqRuV92Hs49j+HnKl/oT5ykJ/EtThRQBuFMlFy95o4nzQk6XdRSQ==,iv:YwOUqBJztuy+Zb/AKvGj167Z/52h19BkL4sIzvxbghA=,tag:e4bFb/u1dFg3tmQNIaHrrA==,type:str]
    known_hosts: ENC[AES256_GCM,data:/btLFKretKfFB9WYNo2u0stRXdZ0ZZaSJ9RturpMJ6wAsbT72eLuI1cWcQL2eOoehePOwoU5l4jByrItZXOStSGIb1k3yWUrd5ejTdcemWf3pg7/s3jWxBHFfKM68yhOYXOp7fLPRi4yG7AE2undQx+phN2VdYhW9PVxEGA/0wg125TtvLA8kc1UVs7S8NPJnWSil+2xD5qKD+ZmFj0gGSoTFgb/6lkSjbq0,iv:1VSGGeDIIPris5jEyhk7idHqzYsJBft2FI2V0Hfp3+U=,tag:TIDNCdHorqq68Jiy5b+EBQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnamFRSTQwdElFRjc3bHox
            R0hpN2praFJ3L3pxSEZsWXlTTDdzUVA0Q0FRCmxyOEJHd2RIUWZJRjg1bE9MQVpW
            dmdFa0pBSDE2c2IyUWxXem45SUoxZk0KLS0tIDZFWmc4WE1XR3VqNUZQejRpSTRn
            MzYyS2FLbDRXZnVaejBQeWlJMmVsNkkKboO5BILOTJ0b5ez0VHmj2stCQ2kUGjkr
            QwK0/zLSaml0nIcCISpUSdK5eH3WKGvhPAoti8lF+p2dMEZSZdejbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T20:49:51Z"
    mac: ENC[AES256_GCM,data:TMJY/tsK4Xb9S68xBZQZuFtKxeukCqytP2GTRIQ59QT28tsiGVjf8C6Sxyy2wayy2Kx0sxyEjAt74YAX/QwBkPwR4IOKDABkZbVEynDeaNI8T0dcnPeKEe5PqJnEtZkB6xUzyk4fKCj0FUmICGhCPsn/in2IUudunEOrl5rcD6Q=,iv:zh2vvJZz7E7L/TO731RP/uinoRRgt/zzRMC/8G6ZySg=,tag:fZKhvrZD3PHi1bp6TiGriw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
