apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:eGVtvXUSAwPbXyGBQu5e9rQRLmIM55y92S4W7qzkRPyla4w4Fm6O21OSZk84dbPhi/uMildcE+R4Yx2tRFyoDXIqnFmA83XVKgFBoNdL0BWlMIlzZu9Pa4ksCmAh3ZTeGhPrm+6kiE9OlLSkgbToAJ5710NiBxmxB7gB/TvS8mSYgJKUh6Dzu71+AgRaY5r/5ehrJAuS6E3R7aGMQQ9CEzNvTxMXbnYJSOfX2QyhRj/DrYBCv4DOPBA6EMg/2RnntQsV/L+FZdi11hGFxd0uONKuBrBQJgNynWIM/Wh5P4xv3dUu8M2NI4wpLt0zbgNi6D9jVclkpBhhUHOJqYOaskbQAsW5uz/JoMRI7zrG7N0p2dQvN5Uer8RzE2g1KEcf,iv:OCjxHk5qLExfRsizCNFQi0YVO15spmQ/FYOGFlBtiIE=,tag:mdeLgvYGujghgXA+RBIBVw==,type:str]
    identity.pub: ENC[AES256_GCM,data:dgfkMJIQkwyABU0eFrGTP09sGVX3woZf+yegFJ/JdN7JRD0ehfr6Mmobm5AjSeE2g/Hkq/WoCZA8S8+heSnnSsh5WaKW5jv5TbHcb695HsrK7VrWvvCQdkFRXeeCMJ50tArYniZhEgJvJqy59huCA/1TSeRGvK2QNmemqeWHkOifFzBE/+v7C/J0HGbKB8PeDZ+habPu00Vla57M+gB1aooUVXkGysCMItuJ9dG9W6JTnEycVz/I+N0qtWTSKSGqxP+biN80oPx5JqRiDg==,iv:aSH73/Jpu5hT8uWcarrfd42LuCiv1f5aQZf6ZByGm4g=,tag:SPGhmBFirXiRKdVOACS/Rw==,type:str]
    known_hosts: ENC[AES256_GCM,data:YfymAg87WiiyLypJbDsGtr4A6zcR3Mz9qndoGL5LD+zMRXREkiwp6pL4gt4kJAAKI2tJrFoXSsO78eX+ffHuX+pXRUNV5fXvwQhATV1jQADpszT/UhlJjdZLvjoBkQ1BeKbNmjleY32lo29DjVd2XWhZMmH3g2/fhJGouDyPzt8YyJXDt9Fpft1gx9779A3L3CXgCFxmZiOjZy0fdxqN+zeuCx4dgAtQRQOm,iv:8GMU1SZXWnkoWdRS2wcVLeTULUJHMiltr6oGYlZzdEI=,tag:ZFljFhpPRzBSwvvAYJtcYA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGd0g5VFYzbUtGOStMSzJv
            WFhQOVlLUmg2MjZwM0pEc2tRY29ic0d6YVdBClNYT3ZKV3NadGJJRWNkRTlLTG9J
            Nm5SRm9tS1pKVWhCWC9yVmtlcDlRREEKLS0tIEJ2MEVQNTZKalB4dFRQdTVvdkoz
            THRnUmM5anF4Q0VWalBDTHpicGZVdEEK3eaeQAa99WNNXby5T/1CiS8rW6Rfks/b
            xxbCNuohk8PpEEjWYMAghCIeRRSeL9V9pBHmpN/aX960w0FFteyHQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T20:55:32Z"
    mac: ENC[AES256_GCM,data:m/aMbK6ItQnU1HM//HAqujduv41J25hnEYfiXP5MdDs7g879WEvQOivnNDeDY5IOtfEJFzmqAJ/3IqmrQf94Y2S3YpqLjGwwZMSAOfBHLN6UsXs3KW66zX3MhvtxHrW5oN+ZbQfaGJjwLsYQHDxOMpNHa6+YLKIDq7VsvQrT3XI=,iv:R4e989Ds9MUV268Ro5DyirKY1NVB3Qv4QZeqA6c45U4=,tag:NrWEEbkgxFCL6kZVPJ0Bsw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
