apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:d4jNsyusKs8AdTgT8CtDkQDt7S55433vY8ams2pzPB9cWIvfQTOW3gcESKJhYqU1IT3H0yPxlTB+hQXjffPG0xcBQo2XYsDcFtSWlXxA6lpemmyExcd7tsjgV5UBx3bJNQDmOuo4GB1vCqk/+Ys4zQ8bcq3OT56v1N/uLMKfGo7hVrqJME1pD7WPrmYTEPN1GBad5YdKj+KNVI1aX+frRvjV62z7rdFGEo+R1Fi8346g+FyXJ81PFPwjayFyXDcxftrQPCt+sk1jwTrGmsOn0XZ27G/pmEJ5+1FwxIVNDWeeYosS0ynOE4I2b9xRcDd/jV7F/UatjOkcLbVQ+FvNOwBIC8n0G4U9YHt9/euuTtVibPMzZ/t5YSz+ZhR+eoM1,iv:jXHqtC55JYfiWw8x5YIdOuPUFbXsQOmkPuWgUVTuJmY=,tag:2dAJKI5A78VsF0a9PoGF/Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:+ppWUnfhjYFyl5zgIUyGZ/R2YWhK+wklSnfKOIEgxq6a7Y5URxEmKJ2z16I8tXHpAX+fIDxdO9gwbKgK+z6R9K4+PheKeKbij2JfgToG9HBYbi4wu5CdYnnMNKgWeavwni4VHeKAxCA+/4PhuQb+lFVOd1Xu0b1JGg40Rq79afcFMZZ4pPFkd+CkRPv7V5alBnKvkNQAr7aCJc5wkwF904tf6sGVG3vhQShaZuXxGINyPxuQncS+Zc4edAgEjOgR8jXc+CeFuhMSy+GW+Q==,iv:sOGmhQq6rDT4FWaJ6I78/f9EUr65XExRB80XeDYUaRg=,tag:pqVm/2uJceGX8pET43Cvpw==,type:str]
    known_hosts: ENC[AES256_GCM,data:4PvbWlCg+j2FA6S7PRjxsuy/rrs66rp2NvYW/npz7ePz9CFd7bowTITIp3szYyZ6LeEFxo8ds6m2fns7ydur9O86mBda/9Z3e6o71rLcdQhfB61qP5D442kcKKJrs55dREdM+YzHDHrWQHsyI1ErXdQLiqVFYm04x3xMD299oCix3tPpnTAMlti5YTqEJlMFzaGrqpdH6LyYTMJMTwGlkrrO1xzAIUwN9n7v,iv:M8eMdXZRHhCkukR3soHzDtM9DQcdTFuDnLeQsslY3Ds=,tag:INwvHO0m+G91exWVH5rc1Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TmpmRE8rd0w2bGhhOGRK
            NVI1RlovSkhzUXovYWlQSE1WQWZkMlE5OXpzCmk4WGJlN3lVZi8vRDZTQzVSYTFq
            TmZrRFlvK3JQYW85Zm5MQ0hhWVpTWUkKLS0tIDErMGZRbm84S0EvRFZKb3Y2MnBS
            QU5rNFhCNVhnLys1VTlVUW5LVDFEOTQKYuZ7jea3vJnrruEwHbRjYsZTMpTnPYsC
            JFxAVUGGLCA4GMWwymQe7cRm7Y0o8AaT7YiqzjrZaD4KKaGiTm4LIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T20:22:40Z"
    mac: ENC[AES256_GCM,data:CFY2fV23FlHcMeu6KwATXKVqQm83opEceY/eTojUyG5qKFoXIoozFz9aDHHrQOxSLuDjy2ad3o+a3tE8TVm7t4KJtvilV9iAkpVKd3S/N0A/sMioE4jhwLiJuOjgiHd5dOlC9zEbt1uDlbaqUSyDA6JtGeF5yFCU/sF/RtNcMcE=,iv:tIU4H6RJB7sf8liSjzqnG8EmBVUOlXGJf57I85kZfik=,tag:Og60UxQgw+Uih4z2UTM8gQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
