apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:FXBI7gLG3h515r21T2iNaWiS43luHWs/AcLTrb5/buysjoCE5ECtRlGm34tM9bDB64fitRjFzpOSFmn8CVKXW3cd7rEiue7rqR+XZxpCbTHzOvTS7DXBPneAinwgdjldEO4gVrU0QvKxS18xEth4CvI6shTenZr7cuq4pRzNbZ89DkqNIi5njNY95r2EsAusnOqU2JtZyOI5UYi5r8y/kD2dynQZf0F517RDPxKXu3u5SXIB/haRaAidWz5qZbKnqTRwRaL8hXNkjhDLWeJVPmdJwcJxg5LblzII0SJqAmZ6P9ep6S4qTD/DX74FYxM5A3qMn4jCid6GdF+PW0rwEYxeTlkiLDzUBshbUmfevSETdjks2tFiPoF091t2ujIE,iv:fvFMLXtT0km6i2W0VOFd7w0VfgR+pnqlWvQif65D0Hs=,tag:2ehlIFTV82JFXYOonPPVxA==,type:str]
    identity.pub: ENC[AES256_GCM,data:bR6en2OAz+eu9eNqRy3Z9dKt12lGy9GL+eIU+xCM5grsL2x22c1sGlDLFHxDeb2MOFnwUjvY+KhPhiSAwrTRhKkl+lIbkYIyfmhoTe6dNrYbVxij1tgoEYQI0ne4Y0gAHCFrVnYpWjuTHHpYMaQySmGVyPeKMMQvRwD1Sro45Iu9E3wNCwSl/5CVsL6BKvYPPd4PnqqpV1EFatGp9szbMcPohkCE10AoWuOJ/gwH3C2b19tPJbeGxOCCAFVrFiuQanLQDriKk9DbRkS2cA==,iv:Ei0NMeZPol4FFCNOR0VTjwxxPb2aynq7Wt3aCrxrQmk=,tag:PHQj4qBPVe6S6Rv9Y23wHA==,type:str]
    known_hosts: ENC[AES256_GCM,data:ZaLi30FRn/P9c03/0BnOSUhT6hzCNmv4+VObLGjJOc2UGxc+OHlzw7XuRSkxT/U7aCjJYZQcozT42Y/hdhA3CmUsPI0afHbgnmQzw1mSuF774v9/3PdaqTfo+VfD2nH4sMeEgZJa+I+1g1cCnJoytvRdLgKL9xWk9G5TQ6zaB4hqL/J1rFKOhdxMA9z7ZJ0nKZMPziy1rUvGhCW5W9oz4XiN1HKfDcUYfOgK,iv:Wlic52zF27aWmGuW7oybNfI/QnD9ZAN/4mOiakDudGc=,tag:8xuif8uFuGoNOvJ94iY8qA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5em5PZFRqcE9CUk1LTWdT
            ZjZCSi9MMk5wRnI3aFF4Wjh0SlA4WGQ4em1JCnR6RGFJQkVkUG92U0gvM2FhV3pH
            aEFIUEtuelVrcDByM2h6NFVnWCt5OTQKLS0tIGc1VTZPT3ZIT2NGNTYzOHBvY0p5
            cGVIYlA3WUJvVW94MGkrRDRVblYwOUUKvNO9sQpED5Kz7PHP0WHmNqWnErVICfI6
            bNQbJF4yN0wGMWdeQPxRy+WWMY7rRLeWnRtJhNDCKTVTthU3ndvd8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T21:19:33Z"
    mac: ENC[AES256_GCM,data:YLSAb7MBZ37SF+fOwN6cEmEqMq9oj5Vwg4g1mv/rcrOJZNEbmRUFhUJ3ozA/TLm8NUFCRAskhvgea2ip+2AEwtTf3pvuRmAyfc83aNwsUlHR6whzSNDg0+WLHm/VFOfLRftD9K4NSZQ7Ky5UyoSKlT0RFSn5gbH1XmpRz0reQNM=,iv:Db8tqdc1UCDjo3j8p637MC/4JArPuJDmsqLpLUsXrN4=,tag:6pb7S5fLYXXP7LMAPjdIcQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
