apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:mWnFwlfE4TEUjefLs6MM4nb6EkJdt9SJPgZ01jPve8ouVqh5x/NzgiHETG5lZLa22TzG6JaD3ABGFZ6z39ClPzjEPzYHqvLZsDry1FYffFFAshLqdrS3CuoiZ8GV9p85tSmcNX/2vtqCdtxWYrcPQz3hfF98ykFb41fNGB5E2Zidci0wUfWy7eHzrNG81OSXTvBRp/W3dVO5X2BBDVtOA6cJvxVPV7uB+L8UFrHE6MNAgz9nYECq5yDqtImw6uXJno/klLVBEFpXP47nEhcgJAOcvU33Hdgox6kFRF6kQqkO0e/APP8tJQmEmrycv++LSSIGppDWVQknqZxVwxDAUdqFCKhW7rBgWQ6ZprrhiGPfXVlYpiAEG22qM5M7w7P3,iv:IohGTx84Ohlo53SzCsOD2bxq9KZoJ5qmUKHruMEo0a8=,tag:sTk7IQKf52O+7ovsAiarTw==,type:str]
    identity.pub: ENC[AES256_GCM,data:1TVwwhYhu+Qu8QFZkOhAjnnI3WbcHXfIXloPvD/uf7NgfpYGmaTMl+TQZXN5S+jxVMh2AXG8wUTyhf2yX20iRFT2a96nI5FY4ZPO56RoJKY2MjNaWe0lZnwSJ3pNHYiwWF/r7ZPJgmizRK7RPJGrt7MWuBEl2fPoXPQUSdG9JL667TqX4nQ8isqR/ICr7mJLyuYvdmXp2N7hyMW7IFchDNeoS4yZfgUoiHjiPRwLTNAYiHeJs6UUeT3U8bfsmc01S4t9Zx//QYJiJJegcw==,iv:H/tljF/SXwEmaDUrAEfyfzkXTBE5nrW0OG2xuF+Sj0E=,tag:LnzfEjBSg5OuRoziB8nBpg==,type:str]
    known_hosts: ENC[AES256_GCM,data:j0gTRmrFdaBGSoUGrzOMPI1kheah6haxRNmUn40FmNRQCGHOSIVid4CYZyIsll6uZFoY2M60eK+0VoT8NCXS/3W+J88PErhuV7TZnYLXB2/e8vTvWmpg8krtTxxjmQ2Au35KEz7o+Vh4Ycb3HMPDn7xeuNOw6WWKJ/j4E58uTqNX8aWenk1ynYPpzYennJCi/9vUbYIlR8F/uiDsfgjRq+fDWSPypMdWNQwi,iv:Kons1Ga0mZd1gaesYRJPswX9fkEP/tF8sDRJJHfRYwg=,tag:+FUbDYDOZdxcTQW52LHxsw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZTJpbEdEQ2ZjWkxIdjdi
            WU1WMGJjZmVjZjBFSFJIOU5pRE9UOWZhS2lzCk02RVF4ZUZmSHpKL2J0eVFKSmVC
            TXF4ejg1T091UFoxWEZpYmdQMWVsVjgKLS0tIHdVd01YYnltWHFSVWFDakFzTXNu
            WTRCL2RWLzFqbmt6c1lYS2d4cmR1SWMK7Hh8YZRpXVw/0DHk7EABoMWP+QSfmnbu
            1HkNbwavvTth8usBBvUCWtIh454GuGel9P5YuS9my2IDzLcLPBCNww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T20:39:04Z"
    mac: ENC[AES256_GCM,data:OJPCIGy+XR0H+hQnlykhMGwO8TG0ArQBjYTJHReRYFifXHXiNAC23bqAuFJLcmT0U4Vs0Tb4vjbZJ4gUNLJXo/AXntPrft4PwXWAlrbmg1C+uSQpynugy06jMLvsLMdVud0n3YF9zbIjw39RTbdxbO1vK7DDvJ3xZfAT/r+3yeg=,iv:eK/fKBS8yqNm7e5AuHwTLvZKr5LI7bqmS9+mUT6yyRQ=,tag:zJrw1Mk4VCehk6zL+/7d3A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
