apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:gaVfgfw+7+Rc/8pbqmn087qpHAiMvZCEd9ssZ+11SmZoznnPe8DIQv5SCLwiNdi5I/HuY7ESCTYe8VxOFqmWyMWsW5gRqmUdKWBEAxLnKh6aB+CLoDaLrq3tyc+9Xgs6FCJPPpFfQOuwGagcPo/n9Aq95DewyqNXHF7cac1ZIpDtPTG52uItgJ2tga8skRxtBcz7UuDchHxdAlT/H7KbKjFJ1zrZKSV3wCYszQwhPR3GyhsJFdopJcGKXa0lvNFdl+A5TQtXHI9S3aVQcISkudD53Fybpb2TcNdlrh96nB4kfI7H8k4Dm9C6uED/EQwP66VAOPSeTNnq8KN8BdW/5Pzpf3n/rrYgVPY7Ys/ZWWhfLM0zt4CR5gXZoW+8hrH6,iv:eaQf0Lqt65zJmmVWuKX4HWT/dcrrnJtDP/kX7r7069o=,tag:6vq5U579emjqdQsHBwaRUA==,type:str]
    identity.pub: ENC[AES256_GCM,data:4wPwU1KTmrSOSBCjAtR9wDx3hFsfQlPk9sEPnILdUteh+jLLhcoJ5L2NkgoQUvHyntqgwd7Y1PIIoOTZeU9tMdOdsasdOcgqYncc6UVPfNPS8ItDqZ8DZvY18by0XN9ASPxU9z6pwl1VmK/DzwHmDExjup7AWjC6dBkyVhhl53hBD7HBz4yvW4HIGVezVN0xDEvxuUKmdjGoaaYAOnPoMQ4CNNVBwvVEAa4wzbnavEQYXZYK+l78Vwq0goPQ2WrxvRPOH6tmFSXuvGy2ww==,iv:V3SzqGv9U5mGRcsN8+di2+YzKcUcHgn6vXQ0f1JMCHY=,tag:ZmsgeoQR/HRtenk6NEeSgQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:d5eEcbxpUSB7b7IEHX8LTQzWmMh7qK6EBL51EZtQe/mUreM0ry9PgIlKRNX/fsAf+z9gUOFbPZKeNpSWKlKIH3rGAj1jMR37SWq8xtuNIiOFZmxtE1OOY0LPF8KWKKV8Ib4MXI7DmVFcc6vDHQOZbCy2SMt8+KZO+R5lOkR4I+Y+eFwvp6RIaR7njRYCb44cnCTwqRpRAyYDCEnxqKQu14ZFbytG9QlHuoHR,iv:igQLUt0QhLkyXEqh4t9sbHK9MDZw4aHnx8uqSlysDzw=,tag:kh1sX+zjwozJ8qf88KUrRQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNHVnWWowYUF3aUFzaGhL
            blBWeEQrcXFsZTk3eHVQS2pzT3hVNzRiclNzCkRYbHkrU1E0Qm5YRTB6TmI4Q2VU
            cHN5ai9xWDlWTGJpeVpkeHUwOEpMNDgKLS0tIEtwRWZ6OGNzMXNCSVlGWmQ4NVJO
            Q0J2SVgzZlljTVljcW1OVTNKcjBoOFUK9mtALGIw4eFB3XyXB2SBb2hf/Zd2MrrG
            U4nq6v7GukapLIXKn6BMbramwXrYxqjSu67lSI6mLUvvG37y6fEk9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T14:44:25Z"
    mac: ENC[AES256_GCM,data:L9pBOO+2qdTHHHbU38XKamP/duthRmfHEQSKwLLsu2G3QOUAr6hY2ycGWMIj/BV8CuWDLlT0lU/hVbeEKxnKuBPIU/mOoBhRvpCuQXmKJ/mUBPRJ769hcZgZ4PA549x3kRMeCobh/jZX2Buu34cs5KFeQf1ILEFsgFws77nWv/4=,iv:puDEC7BBNqT0h+NJLpW1vnCHq+V6dhK342w/E922kdw=,tag:SnpogERUOoKLZH1kfAfuDw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
