apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:6zr8AqQhFZ4ObSUf8XKSfitF9owXqREG91QGQPfl90WV64l4F9SptM4Vs1NEfKGGeb5ArEyn5f2snED0/As1qhcXi8AH71ufReVQHPtoTJEBa8w7StKIw1XV2GgeCHI24BnJwuZ250AHPZbdYYqWvq+r5tXUaIR48TgFkzUYheBnkTZLTAR5G5l32W8oynlza0JNAmV3fwmlLBr6BsECjXzp4h1sXeA2OTceAKYN9be1x9dDIKxibtRsz1AGI+pavenVT5JOVlOm+Mokz0gDluvVpB74ob23/FYgQVSEi5kIWmFIUIWA9IT0xNkN4kOoefS4XR+yFNTD1EbiBVXXI/uT9KZUGqi5R7MTIXLaIXGcz+yIcqhngblaB+/qC3vr,iv:sndB1HDpF0GVqxuT5EbvNOcP+JlJD/VYGoQPBHQmEF4=,tag:aij7vJp6Y+84sUuAlqdDxw==,type:str]
    identity.pub: ENC[AES256_GCM,data:3rc6/VFNuYUmJUbCiEhfQhxOL0S6I26d+vlm9opp+Ssa3ullxM+dDXd05J8+3FQAYQmOVcfzdfdZEUnVujU5tz/sAsMVGH7a5iziOQJROqKHD7cVEqPbc+y3yLZ9Veo9mRqCPFzfzfjJRyuUs0EKYMuGh1XYMCdSravrJVnmcabDgUaK1UC+732nxF1YnSXUlc3vvv03Cd+ztWxkGn23dM3HKa1H8XNPNphgZKvhwbIxJn3ED9ZsV7TMG7ZjAjGOoOGnDJt03Rfovz3rVA==,iv:oCEzi9uh3OLwJhqDg0xQEOF2M5bVNH9bPeyacjCVGSE=,tag:g6nHcthpkQSrgwAxaLhrUQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:J1dC52Pv6DnI8orYSopBRQdlFC963sm3fnA5R93UV5CUUGpe3itbwASxgi973NG0GuByPPnAN4HNrGx6CQ5qAA6zeMDJxYxryuitw1UeFp4Imw+KLwcgvZAkARbTDOmS5553lZik1TUUFzvezQ7zK7moljS5rC/M04AuT37LNRlfIMWqCWCDTby1uLXFKFBnaPCrk7XPUwnCcBkDS/2r5o1HjHUkBwqTM/bZ,iv:2N95RRmPVSquxBjfuEWvqCeOoJ82kYJUr36BT2+1at4=,tag:DfYE/8B2pIla3+Bu3gMgwQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0azBJSHhFYnlrQnV5TGlt
            RlhXVWtnbnZ4c0tLZ05qeTRMVXBNRGU0Z2tJCmFkeUl1SlNWV0dsaVlwbDc2SElm
            Mk5jNzhNS25aRDV5YVNGYTcyT1FyODAKLS0tIHh5ZncwV3NRWlorUXR6SzgwY09Q
            MjZGNWk0Q1NkaEY3MmNQWVNkZjY2OTAK5613UwzRD9Ix1Z2w/rvIJtPgn4e7hMp3
            MMmchlqg+Ra2Bly3pBVofYIuIHbckNlSmK/FxRpIe/I2T7llryggFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T20:54:55Z"
    mac: ENC[AES256_GCM,data:W2EXgc+3/he0wfOK8Pol7lI4qV9pIlEsc1QLitCBUp6sknWB+cUKsPRibcmDhqeYekMCvaCuAacoVvGEqcA//WxAjQCNlH2WIBw766GJA3BnXyBa9rqcZXQT9uDAjEtxdKAlr7JCIA3iBaLCCAIcZ727VAmT/Qh5m02tgeQAAs8=,iv:WVL7ZtwblghXoNkgNzi7eDpY3uB0UFFU3yHep8movLM=,tag:ZgEg0AlbhlFASUF10DA2Aw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
