apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:9jRixybCxU/wtkGeHOF6xRKc4Q24sFvpo/q6o10j2n8u86eB/jpLT5uyghWxw+91Yt8cjB7CSjYWZ05I0+MOcfxsb4+E9CSJQeivF8FhLBjcHvU6BsJEcAcw+hY4piw/qO3Sz4hQ4Ccko/bWBtbv5w86jEWySXhSLdVl2Zid2qY9Icabedc71dQywIRAlTRhVUkF1AxPyEKIztPhwYcfOCTcF6csgriVe7z5F7tBavCV8e2dySdGIzOGl1Cz0zclp2E8RFySZHLmdslPi23AK2lSwJ1a8XIeb56N228Axqx7uhGQ/WIqkwTKVVelGHiv+QlPKN/F5L2VD0uLFu5vNW+5iwfOZxETlL7kknaRuQE2GxBp77EITASJW6npCR/y,iv:Nt8yJfAEEjrIUqq3eU46vSRIX/0vdghPnbdJZWadvB4=,tag:rqFt7V8O7S4uPkbbm56pMw==,type:str]
    identity.pub: ENC[AES256_GCM,data:X6yaB7ZDRTqiMV66Se5jpawGOftfjV4DSVt9/Vu5a35Y1OMmg+ICDSWaIyc20II8kQ4BIyjH9huarnQiS7/CQmErTnkrtbUk8CNJmaixF/03zfy63ptj+cWUVbas/MfdlYcktj9lngQO1+yvQcyLdFzXcm3U6colT70sSEs7StN3yEF6mbY3hF4nFal7s8CFbcC52nxlHjRWa4ZsSUiGQOIrXmuXJIwJVRpeLsCjpJqhuk9RT+YElUmuI8NMR6JdGyB6nxYlLHNhGxCRgQ==,iv:diumE7v3EtHLuV594oZ+fpisVmjKdBrXy372ODUhuCc=,tag:ul5+BSpcL8pEJ9LGmJ/1Mw==,type:str]
    known_hosts: ENC[AES256_GCM,data:dW3cEO6qEeCUKh+oaDFFLGu3PuKIK+D1McuAfA4iZH8ejBVLufhpYDC3KQDvqIK4BFGomBMkBsAIftW1iSwJNaxC8NLhX8QNIc0aa9ejfJwJYSbg4IiQISFYBvG9ubEK8j/yIxZYp+WA9wMw+S9KXw9T3o4nECYuge+JwDYfI2G4gZ3CFT7FsWxPbBa2Qz8TlULcC9K2CamQdUXi60W7wO6iSMawLyUurKcf,iv:WxVq908uqwWRnAWNxKuEb4fcZoR5WBMxhSxcJFZPFkM=,tag:/4Z47/q2kLnN1a/ZaTSaTQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSDhBVU16TDdmazgzWm9L
            ZmdCZ0xRQ2dtYXlkZG9ES2wvZDQvd1FrNHhFCnlwMGhhZHd1QzZzZ0FqcUYxM2tV
            SGNBT0FONkwxK1JQTytLcHVKRnk0cGMKLS0tIEdHZUVVaStzR1ZZUjc4NXZKUTVm
            cVZqcE55Z2NSdFc1Wm94eVlFWk9mSVEKa74/o2uGDEI0cYYSlEQn3ZTNA5CLyah4
            mtwAQc6/fB3FETzGo6ylGVaqvySrWNePzSiwnRkzF8LZNOJNzG4v8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T21:03:50Z"
    mac: ENC[AES256_GCM,data:zfBgeafcKC5n44dXh9oRYPHUmRFqKFTSeFV7XISfM8pKxFzxepZGBhm/4YK+2yelnAjnqPP4Sk4RNVeZ7nJ+qKhEputxymGz8GvT0rwZY0T93T1AZQ5iDPUgyNDHdI1+aOHKKaJy9Y78AqC+aTE5w+vfUYkTVVKPqN/uInKljLk=,iv:Y6LZp63Cc6jgKsryw0Ed/xdXgM54LfRaGT+VPrC3TIU=,tag:xL9evGt1Q9dMqiLxdkJh4w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
